# Generated by Django 4.2.15 on 2025-05-31 16:32

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="GB", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country_of_birth",
            field=django_countries.fields.CountryField(
                default="GB", max_length=2, verbose_name="Country of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_expiry_date",
            field=models.DateField(
                default=datetime.date(2025, 1, 1),
                verbose_name="ID or Passport Expiry Date",
            ),
        ),
    ]
