services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
    command: /start.sh
    networks:
      - banker_local_nw
  
  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - banker_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - banker_local_nw
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - ./.envs/.env.local
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - banker_local_nw
  
  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - banker_mailpit_db:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - banker_local_nw

  nginx:
    build: 
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - nginx_logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - banker_local_nw

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    

networks:
  banker_local_nw:
    external: true

volumes:
  banker_local_db:
  banker_mailpit_db:
  pgadmin_data:
  nginx_logs_store:
  portainer_data:



